<p>I am going through selenium practice where xpath validates in <a href="https://code.google.com/p/xpathchecker/" rel="nofollow">firefox xpath extesion</a> but not in python selenium.</p>  <p>e.g. go to <a href="http://www.hotleathers.com/Front-Printed-T-Shirts-C1232.aspx?s=OrderBy%20ASC&amp;&amp;v=all" rel="nofollow">here</a> and apply xpath <code>//span[@class='tableNode']/text()[preceding-sibling::br and following-sibling::br]</code> it works in firefox extension but not in selenium expression like <code>driver.find_elements_by_xpath("//span[@class='tableNode']/text()[preceding-sibling::br and following-sibling::br]")</code></p>  <p>Exception i am facing </p>  <pre><code>    Traceback (most recent call last):       Debug Probe, prompt 17, line 1       File "C:\Python27\ArcGIS10.3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 270, in find_elements_by_xpath         return self.find_elements(by=By.XPATH, value=xpath)       File "C:\Python27\ArcGIS10.3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 739, in find_elements         {'using': by, 'value': value})['value']       File "C:\Python27\ArcGIS10.3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute         self.error_handler.check_response(response)       File "C:\Python27\ArcGIS10.3\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 181, in check_response         raise exception_class(message, screen, stacktrace)     selenium.common.exceptions.InvalidSelectorException: Message: The given selector //span[@class='tableNode']/text()[preceding-sibling::br and following-sibling::br] is either invalid or does not result in a WebElement. The following error occurred:     InvalidSelectorError: The result of the xpath expression "//span[@class='tableNode']/text()[preceding-sibling::br and following-sibling::br]" is: [object Text]. It should be an element. </code></pre>  <p>Any help is welcome.</p>