<p>I have a python application that run perfectly on python IDE. It makes serial communication with an external device.</p>  <pre><code>import serial, string port = serial.Serial("/dev/ttyUSB0", 38400, timeout=10.0) serial.PARITY_NONE serial.EIGHTBITS serial.STOPBITS_ONE   #Set Rotor size  port.write(bytes([53, 4, 36, 0, 83])) print("Set Rotor size") data = port.read(20) data1= list(data) print(data1) </code></pre>  <p>I get the following correct output</p>  <blockquote>   <blockquote>     <blockquote> <pre><code>Set Rotor size [53, 1, 4, 0, 83, 53, 27, 0, 132, 83] </code></pre>     </blockquote>   </blockquote> </blockquote>  <p>But when I try to run in the linux terminal, I get different output which is wrong.</p>  <pre><code>pi@raspberrypi /home/python $ python serialcomm.py Set Rotor Size ['[', '5', '3', '\xff', ' ', ',', ' ', '8', '3', ']', ',', ' ', '8', '\xff',     ']'                                                                                                             , ',', '\x1b', '\x01', '\x84', ']'] </code></pre>