<p>I have a service that makes use of the Scala Async library. I'm using this library primarily to time my database calls. The method that I want to test contains multiple calls to the database using the async await mechanism. A pseudo code of what I have is as below:</p>  <pre><code>def myDbMethod() = async {   val firstCall = await(call the db and get the result)    val secondCall = await(all the db and get the result)    val thirdCall = await(all the db and get the result)   ... } </code></pre>  <p>In my Scala test unit test, I have </p>  <pre><code>Await.result(myDbMethod(), 10.seconds) </code></pre>  <p>I was just trying to debug myMethod by running my unit test which would return with a test success even before getting into the secondCall. I mean I had breakpoints in all the 3 calls to the database, but the IntelliJ debugger would just exit out as soon as it finishes the first call to the database. Why is this? How can I test this behaviour using IntelliJ debugger?</p>